name: Minimal Test (reusable)

on:
  workflow_call: {}

jobs:
  echo:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - run: echo "hello from reusable workflow"
